# Generated by Django 2.0.5 on 2018-08-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0002_auto_20180816_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_users',
            name='isHotel_representative',
            field=models.BooleanField(default=False),
        ),
    ]
