# Generated by Django 2.0.5 on 2018-08-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0003_auto_20180817_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='hotel_id',
            field=models.IntegerField(default=0),
        ),
    ]
