# Generated by Django 2.0.5 on 2018-08-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0004_booking_details_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='Mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
